### PR TITLE
Add subscriber publisher

### PR DESCRIPTION
**Pull request by poggenhans**
Please don't hate me - I have another PR. This one adds the functionality to do the subscribing and advertising directly with the rosparam_handler via the new `add_subscriber` and `add_publisher` functions. I'll also open a PR in the tutorial repo for a demonstration. 

I implemented this for python too, therefore this PR depends on #20.

### CODE REVIEW

**Comment by artivis** [comment]
Just dropping my two cents.  
Is it actually the right place for subscribers/publishers ? Everything here relates to parameters.
Wouldn't it be more appropriate to create a new package / class etc, say `rostopic_handler` ??  
You could even move a step forward and create a meta-package `rosnode_handler` to which both `rosparam_handler` & `rostopic_handler` would be part of.

Don't get me wrong, I like the idea :+1:.  
It somewhat relates to the unfinished project  [catkin_create_pkg_advanced](https://github.com/awesomebytes/catkin_create_pkg_advanced) we started long ago with @awesomebytes.

Thanks for the work !

**Comment by cbandera** [comment]
The default branch and the [contribution guidline](https://github.com/cbandera/rosparam_handler/blob/develop/README.md#contribution) have changed.
Please pull the latest changes from develop and create a new PullRequest against the new default branch. Thank you.

**Comment by poggenhans** [comment]
@cbandera I have updated my branch to match the contribution guideline. This can be reopened.

However I have to point out one discrepancy between C++ and python in my implementation in the way relative topics are handled. If *my_topic* is specified as topic for a node living in */my_ns/my_node*, the C++ version will end up subscribing to */my_ns/my_node/my_topic* (which I think is intuitive), while the python version subscribes to */my_ns/my_topic*, because there is no private NodeHandle in python. 

To achieve the same with python, the parameter name would have to be *~my_topic*, which again does not work for C++ (will throw an exception).

To solve this, the python implementation could silently add a *~* to relative topic parameters (e.g. those not starting with a */*), but I am unsure if this is really the more intuitive solution for a python user.

**Comment by poggenhans** [comment]
@artivis I agree that this is an enhancement that expands the boundaries of what rosparam_handler wants to be, but I think that this is the best place for such a feature. This is still closely related to parameter handling, because internally it extensively uses add_param to provide parameters for topics and queue sizes.

The only thing that goes beyond this is that it also creates actual subscriber and publisher objects. And by doing that it relieves node programmers of a lot of error-prone boilerplate code. 

What it also does is that it makes the rosparam_handler capable of generating all the common interfaces to the ROS world, with just one *.param* file. And makes it makes a node a lot more self documenting, because all you have to do is look at the *.param* file to see what topics a node offers/requires and which parameters it uses.

**Comment by artivis** [comment]
@poggenhans I am definitely in favor of alleviating error-prone boilerplate code from the developer.  
Once again my only point here is that it is somewhat confusing to have subscriber/publisher within an object which very type's name contains `parameter`...  
With little effort you could simply create a new class `topic_handler` or whatever the name with a new appropriate template header. Then it would be clear for the developer that `rosparam_handler` deals with params and `topic_handler` with topics ...

**Comment by poggenhans** [comment]
@cbandera Unittests were broken after the last merge, I fixed them now. What are your plans with this PR?

**Comment by cbandera** [comment]
Hi @poggenhans, thanks for the work and sorry for taking so long to merge this.  wanted to merge the smaller PRs first.
Concerning my plans: I am still not really sure. I do like the functionality, but I agree with @artivis that it should go into it's own module. 
Now the question is:
- Should it go into it's own CMake Package?
- Should it go into it's own Configfile?
- If the answer to both questions above is no: Should we at least create two classes, one to hold the parameters and one to hold the subscribers, which could then take a reference to the parameter class for retrieving the topic name?

Maybe the last option is the best. This would keep the functionality separated, while reusing the existing module. What do you think? Would that work for you?

**Comment by poggenhans** [comment]
The thing is that parameter handling and subscription handling is very closely related. If we would try to split this completely, the new "subscription_handler" whould:
*  have to handle all the parameters for subscribing by itself in just the same way the _rosparam_handler_ does, e.g. we would have to replicate the rosparam_handler behaviour,
*  be a seperate generator object so that a user would have to use two different generator objects in his _*.param_ file,
*  be unable to check naming conflicts between a topic parameter and a normal parameter

If you really wish to keep things seperate, having a separate param-class and a subscriber-class might be an option, but the reference would have to be bi-directional, because the param object needs to inform the subscriber object when topic names (and queue size, tcp settings, ...) have changed by dynamic reconfigure. I am not sure if a structure like that would be a pain to maintain in the future. And also a permanent source of irritation for people using this.

If you want to keep things cleaner, I would propose to move the subscriber objects to a sub-class that is held by the parameter-class. So that the subscribers can be accessed as `my_params.subscribers.my_subscriber` and `my_params.advertisers.my_advertiser`. Whould this be a solution?

As you might have imagined, I have already played around with this feature and my impression is that it really makes new nodes much easier to implement. Especially for beginners, because it keeps a lot of ROS programming details (and traps) away from them.

**Comment by artivis** [comment]
This PR has been addressed as a new package [rosinterface_handler](https://github.com/KIT-MRT/rosinterface_handler). Thus closing it.

**Pull request closed without merging**
