### PR TITLE
Fix wrong error message

### LINKED ISSUE #47: Error: "Parameter 'foo/bar' is not defined."
With the release of version 0.1.2. this week, I get errors for all parameters listed in a .params file when launching my stack.

Location:
`src/rosparam_handler/include/rosparam_handler/utilities.hpp:getParam:136`

### PR DESCRIPTION
**Pull request by artivis**
Do not print error message while retrieving a param with default value.

Fix #47 .

### CODE REVIEW

**Comment by beetleskin** [comment]
Is this going to be merged and deployed anytime soon?

Btw, I get the error when I try to instantiate the param struct manually:

```cpp
ros::NodeHandle pnh("~");
my_package::MyNodeParameters params(pnh);
params.fromParamServer();
```

Is there a better way of doing it, maybe withouth NodeHandle? I just want to get the struct with the default values.

**Comment by artivis** [comment]
Indeed this has been pending for a while now, my bad.
I'll try to take care of it this weekend :+1:.

The current API does not offer the possibility to instantiate the default values without a `NodeHandle`. However I think this would be fairly doable, again I'll see what I can do over the weekend.

**Comment by artivis** [comment]
@beetleskin FYI I will wait some more changes before releasing again (hopefully #37) as the issue this PR fixes is annoying but not critical.

Notice that #37 also initializes parameters with default value at construction time cutting the need from calling `params.fromParamServer()` to use them : 
```cpp
my_package::MyNodeParameters params(ros::NodeHandle("~"));
my_var_with_default = params.my_var_with_default;
```

I'll evaluate later the need & implications of a `NodeHandle`-free constructor...

**Comment by beetleskin** [comment]
seems legit, thanks!

**Comment by beetleskin** [comment]
any release date in sight here? :)

**Comment by beetleskin** [comment]
.. not?

**Comment by artivis** [comment]
Hi there, 
I'm currently on vacation. Ill take care of releasing it in a couple weeks, after merging #56. 
Sorry for the late answer / delay.

**Comment by artivis** [comment]
@beetleskin FYI release 0.1.4 is on the way for [Indigo](https://github.com/ros/rosdistro/pull/19031)/[Kinetic](https://github.com/ros/rosdistro/pull/19032) & [Lunar](https://github.com/ros/rosdistro/pull/19033) :+1:.

**Pull request merged**
